name: Auto Merge

on:
  schedule:
    - cron: "0 12 * * 1-5"     # every weekday (Monâ€“Fri) at 12:00 UTC
    - cron: "0 12 * * 1-2"     # every Monday & Tuesday at 12:00 UTC
    - cron: "0 12 11 * *"      # every 11th of the month at 12:00 UTC
    - cron: "0 12 18 * *"      # every 18th of the month at 12:00 UTC
    - cron: "0 12 20 * *"      # every 20th of the month at 12:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  auto-pr:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          echo "Updated at $(date)" >> auto-update.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: auto update"
          branch: "auto-update-${{ github.run_id }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto Update"
          body: "This PR was created automatically."
          base: main

      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.BOT_TOKEN }} # Bot PAT here
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Merge PR
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --squash --admin --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
